version: '3.1'

services:
  
  # Jaeger
  jaeger-all-in-one:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Otel Collector
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
  
  client-api:
    image:  localhost/eyassir/client-api:latest
    build:
      context: ./client
    environment:
      - SERVER_URI=http://server-api:5000
      - OTLP_URI=http://otel-collector:4317
    ports:
      - 10000:10000
    depends_on:
      - server-api
  
  server-api:
    image:  localhost/eyassir/server-api:latest
    build:
      context: ./server
    environment:
      - OTLP_URI=http://otel-collector:4317
  